# Generated by Django 5.0.3 on 2026-05-22 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='fa-solid fa-graduation-cap', help_text="Font Awesome class for the icon (e.g. 'fa-brands fa-python')", max_length=100)),
                ('glow_color', models.CharField(choices=[('purple', 'Neon Purple'), ('blue', 'Neon Blue'), ('pink', 'Neon Pink'), ('green', 'Neon Green')], default='purple', help_text='Color class used for neon shadow and background animations', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short bio about the student', max_length=500)),
                ('branch', models.CharField(blank=True, help_text='Department or engineering branch (e.g., Computer Science, Data Science)', max_length=100)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of interests/skills (e.g., Python, UI/UX, DSA)')),
                ('profile_image', models.ImageField(default='profile_images/default_avatar.png', upload_to='profile_images/')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('badges', models.ManyToManyField(blank=True, related_name='profiles', to='users.badge')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='users.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
