# Generated by Django 5.0.3 on 2026-05-22 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(help_text='Write your notes, post caption, or question here.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('category', models.CharField(choices=[('Coding', 'Coding 💻'), ('Notes', 'Notes 📝'), ('AI/ML', 'AI/ML 🤖'), ('Projects', 'Projects 🚀'), ('Internship', 'Internship 💼')], default='Notes', help_text='Category/discipline tag for filtering posts', max_length=50)),
                ('ai_summary', models.TextField(blank=True, help_text='Automated summary of notes generated by StudySphere AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
