from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    """
    Model representing a study post shared by a student on StudySphere.
    Supports file uploads, tags, likes count, and automated AI summary.
    """
    CATEGORY_CHOICES = [
        ('Coding', 'Coding 💻'),
        ('Notes', 'Notes 📝'),
        ('AI/ML', 'AI/ML 🤖'),
        ('Projects', 'Projects 🚀'),
        ('Internship', 'Internship 💼'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    caption = models.TextField(help_text="Write your notes, post caption, or question here.")
    image = models.ImageField(upload_to="post_images/", blank=True, null=True)
    category = models.CharField(
        max_length=50, 
        choices=CATEGORY_CHOICES, 
        default='Notes',
        help_text="Category/discipline tag for filtering posts"
    )
    ai_summary = models.TextField(
        blank=True, 
        help_text="Automated summary of notes generated by StudySphere AI"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name="liked_posts", blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.user.username}'s {self.category} Post ({self.id})"

    @property
    def total_likes(self):
        """Helper returning the number of users who liked this post."""
        return self.likes.count()
