from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import UserProfile, Badge
from posts.models import Post

def splash(request):
    """
    Renders the animated high-fidelity splash screen of StudySphere.
    Auto-redirects based on authorization cookie after 3.2s.
    """
    return render(request, 'splash.html')


def register_view(request):
    """
    Handles student registration.
    Creates a User and fills branch & skills within the auto-generated UserProfile.
    """
    if request.user.is_authenticated:
        return redirect('feed')
        
    if request.method == 'POST':
        username = request.POST.get('username', '').strip()
        email = request.POST.get('email', '').strip()
        password = request.POST.get('password', '')
        branch = request.POST.get('branch', '')
        skills = request.POST.get('skills', '').strip()
        
        # Simple Validation
        if not username or not email or not password or not branch:
            messages.error(request, "All required fields must be filled out.")
            return render(request, 'users/register.html')
            
        if User.objects.filter(username=username).exists():
            messages.error(request, "Username is already taken.")
            return render(request, 'users/register.html')
            
        if User.objects.filter(email=email).exists():
            messages.error(request, "An account with this email already exists.")
            return render(request, 'users/register.html')
            
        # Create user
        user = User.objects.create_user(username=username, email=email, password=password)
        
        # Access profile (automatically generated by Django signals)
        profile = user.profile
        profile.branch = branch
        profile.skills = skills
        profile.save()
        
        # Auto-login newly registered user
        login(request, user)
        messages.success(request, f"Welcome to StudySphere, {username}! Your workspace is active.")
        return redirect('feed')
        
    return render(request, 'users/register.html')


def login_view(request):
    """
    Authenticates user and signs them in.
    """
    if request.user.is_authenticated:
        return redirect('feed')
        
    if request.method == 'POST':
        username = request.POST.get('username', '').strip()
        password = request.POST.get('password', '')
        
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, f"Welcome back, {username}!")
            return redirect('feed')
        else:
            messages.error(request, "Invalid username or password.")
            
    return render(request, 'users/login.html')


@login_required
def logout_view(request):
    """
    Signs user out of the platform session.
    """
    if request.method == 'POST':
        logout(request)
        messages.success(request, "Logged out successfully. See you soon!")
        return redirect('splash')
    return redirect('feed')


@login_required
def profile(request, username):
    """
    Renders user profile space with glowing badges, followers counts,
    and a custom seed panel allowing manual badge assignment for own profiles.
    """
    target_user = get_object_or_404(User, username=username)
    user_profile = target_user.profile
    user_posts = Post.objects.filter(user=target_user)
    
    # Assess contextual details
    is_owner = (target_user == request.user)
    is_following = request.user.profile.following.filter(id=user_profile.id).exists()
    
    # Fetch all badges in DB for manual assignment panel (visible to owner only)
    all_badges = Badge.objects.all()
    
    context = {
        'profile': user_profile,
        'posts': user_posts,
        'is_owner': is_owner,
        'is_following': is_following,
        'all_badges': all_badges,
    }
    return render(request, 'users/profile.html', context)


@login_required
def edit_profile(request):
    """
    Allows user to edit their biography, department branch,
    interests tags, and upload a profile picture.
    """
    user_profile = request.user.profile
    
    if request.method == 'POST':
        bio = request.POST.get('bio', '').strip()
        branch = request.POST.get('branch', '')
        skills = request.POST.get('skills', '').strip()
        profile_img = request.FILES.get('profile_image')
        
        user_profile.bio = bio
        user_profile.branch = branch
        user_profile.skills = skills
        if profile_img:
            user_profile.profile_image = profile_img
            
        user_profile.save()
        messages.success(request, "Student profile updated successfully!")
        return redirect('profile', username=request.user.username)
        
    return render(request, 'users/edit_profile.html', {'profile': user_profile})


@login_required
def assign_badges(request):
    """
    Handles POST requests to manually assign badges.
    This fulfills the requirement: 'Allow manual badge assignment'.
    """
    if request.method == 'POST':
        badge_ids = request.POST.getlist('badges')
        user_profile = request.user.profile
        
        # Clear existing badges and set the newly selected ones
        user_profile.badges.clear()
        for b_id in badge_ids:
            try:
                badge = Badge.objects.get(id=b_id)
                user_profile.badges.add(badge)
            except Badge.DoesNotExist:
                pass
                
        messages.success(request, "Achievement badges assigned and saved successfully!")
        
    return redirect('profile', username=request.user.username)


@login_required
def followers_following(request, username):
    """
    Displays lists of followers or following students.
    """
    target_user = get_object_or_404(User, username=username)
    active_tab = request.GET.get('tab', 'followers')
    
    if active_tab == 'following':
        # People whom the target user is following
        profiles = target_user.profile.following.all()
    else:
        # People who are following the target user
        profiles = target_user.profile.followers.all()
        active_tab = 'followers' # fallback
        
    context = {
        'target_user': target_user,
        'profiles': profiles,
        'active_tab': active_tab,
    }
    return render(request, 'users/followers_following.html', context)
